### ISSUE TITLE
Retreive seed screen not showing all keywords

### ISSUE THREAD

**Issue by kangaderoo** [ZeroPointThree17/radbag-wallet#1]
I used the retreive seed function and notished that not all keywords were displayed on my screen.
This could be due to my screen resolution (Samsung Galaxy S7 edge = 2560x1440)
The result of this function required 3 lines to print all the words, 
but the third line overlaps with the bottom menu, and the windows showing the seed keys does not scroll.
In landscape mode this effect it seven worse.

**Comment by ZeroPointThree17** [comment]
This has been noted and will be fixed in the next update of the app.  The fix will introduce more scrollable area in the "Show Mnemonic" Screen.   More scrollable space will also be incorporated into the "New Wallet" screen, since the mnemonic is shown there too.

**Comment by ZeroPointThree17** [comment]
See latest release 2.9.4 which addresses this issue and is on google play store now. Will be out on Apple store later today/early tomorrow (pending Apple approval).
