### ISSUE TITLE
Support for 18 and 24 word seeds

### ISSUE THREAD

**Issue by kangaderoo** [ZeroPointThree17/radbag-wallet#5]
to be more compatible with the official wallet support for 18 and 24 word seeds would be nice.

**Comment by ZeroPointThree17** [comment]
Will leave this open for now as a reminder.  Other higher priority features are being worked on by our team currently, but I agree it would be good to have to achieve parity with the Desktop wallet.

**Comment by kangaderoo** [comment]
V 2.13
